#!/usr/bin/env node
var exec = require('child_process').exec,
    cwd = process.cwd(),
    fail = '\x1B[31mfailed!\x1B[39m',
    ok = '\x1B[32mok\x1B[39m',
    notfound = '\x1B[33mn/a\x1B[39m (no script found)';

function getRoot() {
    exec('git rev-parse --show-toplevel', function (err, stderr, stdout) {
        if (err) {
            console.log('failed to find git root');
            process.exit(1);
        }
        var path = stderr.trim(),
            config = require(path + '/package.json');
        runJshint(stdout, config);
    });
}

function runJshint(path, config) {
    exec('./node_modules/precommit-hook/node_modules/.bin/jshint .', { cwd: path }, function (err, stdout, stderr) {
        if (err) {
            console.log('jshint: ' + fail);
            console.log(stdout);
            console.log(stderr);
            process.exit(1);
        } else {
            console.log('jshint: ' + ok);
            runValidator(path, config);
        }
    });
}

function runValidator(path, config) {
    if (config.scripts && config.scripts.validate) {
        exec(config.scripts.validate, { cwd: path }, function (err, stdout, stderr) {
            if (err) {
                console.log('validation: ' + fail);
                console.log(stdout);
                console.log(stderr);
                process.exit(1);
            } else {
                console.log('validation: ' + ok);
                runTests(path, config);
            }
        });
    } else {
        console.log('validation: ' + notfound);
        runTests(path, config);
    }
}

function runTests(path, config) {
    if (config.scripts && config.scripts.test) {
        exec(config.scripts.test, { cwd: path }, function (err, stdout, stderr) {
            if (err) {
                console.log('tests: ' + fail);
                console.log(stdout);
                console.log(stderr);
                process.exit(1);
            } else {
                console.log('tests: ' + ok);
                process.exit(0);
            }
        });
    } else {
        console.log('tests: ' + notfound);
        process.exit(0);
    }
}

console.log('running pre-commit checks...');
getRoot();
